SIJARTA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hijau/', include('hijau.urls')),
    path('kuning/', include('kuning.urls')),
    path('', include('landing_page.urls')),
    path('mypay/', include('merah.urls')),
    path('biru/', include('biru.urls')),
    path('test', include('testquery.urls')),
]

biru/urls.py
from django.urls import path
from biru.views import *

app_name = 'biru'

urlpatterns = [
    path('diskon/', diskon, name='diskon'),
    #path('testimoni-form/', testimoni_form, name='testimoni_form'),
    path('pembelian-voucher/', pembelian_voucher, name='pembelian_voucher'),
    path('testimoni-cards/', testimoni_cards, name='testimoni_cards'),
    path('testimoni-form/<str:id_pemesanan>/', testimoni_form, name='testimoni_form'),
]

hijau/urls.py
from django.urls import path
from . import views

app_name = 'hijau'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('subcategory/<str:category_id>/<str:subcategory_nama>/', views.subcategory_detail, name='subcategory_detail_user'),
    path('join-subcategory/<str:subcategory_id>/<str:pekerja_id>/', views.join_subcategory, name='join_subcategory'),
    path('worker/<str:worker_name>/', views.worker_detail, name='worker_detail'),
    path('create-pemesanan/<str:subcategory_id>/<str:session>/<str:price>', views.create_pemesanan, name='create_pemesanan'),
    path('view-pemesanan/', views.view_pemesanan, name='view_pemesanan'),
    path('batal-pemesanan/<str:id_pemesanan>/', views.batal_pemesanan, name='batal_pemesanan'),
]

hijau/views.py
import uuid
from django.shortcuts import get_object_or_404, redirect, render
from django.http import Http404, HttpResponse, JsonResponse
from datetime import date, datetime
from django import forms
from utils.query import query
from urllib.parse import unquote

def homepage(request):

    #query kategori
    query_str = f"""
    select * from kategori_jasa
    """
    categories = query(query_str)

    #query subkategori
    query_str = f"""
    select * from subkategori_jasa
    """
    subcategories = query(query_str)

    #pengguna lagoin
    penggunalogin = request.session.get('penggunalogin')

    context={
        'categories': categories,
        'subcategories': subcategories,
        'penggunalogin': penggunalogin,
    }
    return render(request, 'homepage.html', context)

# View for user
def subcategory_detail(request, category_id, subcategory_nama):
    penggunalogin = request.session.get('penggunalogin')

    # Ubah %20 menjadi spasi
    subcategory_nama = unquote(subcategory_nama)
    
    #query kategori
    query_str = f"""
    select * from kategori_jasa
    where id_kategori_jasa = '{category_id}'
    """
    categories = query(query_str)

    #query subkategori
    query_str = f"""
    select * from subkategori_jasa
    where nama = '{subcategory_nama}'
    """
    subcategories = query(query_str)

    #query sesi_layanan
    query_str = f"""
    select * from sesi_layanan
    where id_subkategori = '{subcategories[0]['id_subkategori_jasa']}'
    """
    sessions = query(query_str)

    #query testimoni
    query_str = f"""
    select pgn1.nama as namapengguna, pgn2.nama as namapekerja, tst.tgl as tanggal, tst.teks, tst.rating
    from tr_pemesanan_jasa tpj
    join pengguna pgn1 on tpj.idpelanggan = pgn1.id_user
    join pengguna pgn2 on tpj.idpekerja = pgn2.id_user
    join testimoni tst on tpj.id_tr_pemesanan_jasa = tst.idtrpemesanan
    where tpj.idkategorijasa = '{subcategories[0]['id_subkategori_jasa']}';
    """
    testimonials = query(query_str)

    #query testimoni
    query_str = f"""
    select pgn.nama
    from pekerja_kategori_jasa pkj
    join pengguna pgn on pgn.id_user = pkj.pekerjaid
    where pkj.kategorijasaid ='{categories[0]['id_kategori_jasa']}';
    """
    workers = query(query_str)
    
    joined = False

    for worker in workers:
        if(worker['nama'] == penggunalogin['nama']):
            joined = True

    context={
        'category_name': categories[0]['namakategori'],
        'subcategory': subcategories[0],
        'penggunalogin': penggunalogin,
        'sessions': sessions,
        'testimonials': testimonials,
        'workers': workers,
        'joined': joined,
    }

    if(penggunalogin.get('role') == 'pengguna'):
        return render(request, 'subcategory_user.html', context)
    else:
        return render(request, 'subcategory_worker.html', context)

def join_subcategory(request, subcategory_id, pekerja_id):
    penggunalogin = request.session.get('penggunalogin')
    #query subkategori
    query_str = f"""
    select * from subkategori_jasa
    where id_subkategori_jasa = '{subcategory_id}'
    """
    subcategories = query(query_str)

    query_str = f"""
    insert into pekerja_kategori_jasa values(
    '{pekerja_id}', '{subcategories[0]['kategorijasaid']}')
    """
    hasil = query(query_str)
    
    # Respons JSON
    try:
        # Operasi sukses
        return JsonResponse({
            'status': 'success',
            'message': f'Berhasil bergabung',
            'pekerja_nama': penggunalogin['nama'],  # Gantilah ini sesuai dengan data yang benar
        })
    except Exception as e:
        return JsonResponse({
            'status': 'error',
            'message': str(e),
        })

def worker_detail(request, worker_name):
    penggunalogin = request.session.get('penggunalogin')

    worker_name = unquote(worker_name)

    query_str = f"""
    select * from pengguna
    join pekerja on id_user = id_pekerja
    where nama = '{worker_name}'
    """
    pekerja = query(query_str)

    context = {
        'pekerja': pekerja[0],
        'penggunalogin': penggunalogin,
    }
    
    return render(request, "worker_detail.html", context)
class PemesananForm(forms.Form):
    query_str = f"""
    select * from metode_bayar
    """
    metode_pembayaran = query(query_str)

    diskon = forms.CharField(
        max_length=100, 
        required=False, 
        label="Diskon (Opsional)",
        widget=forms.TextInput(attrs={
            'class': 'w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#2C5F59]',
            'placeholder': 'Masukkan kode diskon jika ada'
        })
    )
    metode_bayar = forms.ChoiceField(
        choices=[(metode['id_metode_bayar'], metode['nama']) for metode in metode_pembayaran],
        label="Metode Pembayaran",
        widget=forms.Select(attrs={
            'class': 'w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#2C5F59]'
        })
    )
    
    # Optional: Button style for submit
    submit_button = forms.CharField(widget=forms.HiddenInput(), initial="Submit", required=False)

def create_pemesanan(request, subcategory_id, session, price):
    penggunalogin = request.session.get('penggunalogin')
    tanggal_pemesanan = date.today()
    context = {
        'tanggal_pemesanan': tanggal_pemesanan,
        'harga': price,
        'penggunalogin': penggunalogin,
    }
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        form = PemesananForm(request.POST)
        if form.is_valid():
            # Ambil data dari form
            diskon_code = form.cleaned_data.get('diskon', '')  # Default '' jika kosong
            metode_bayar = form.cleaned_data['metode_bayar']
            harga_akhir = float(price)  # Default harga adalah harga awal
            berhasil_diskon = False

            # Cek apakah kode promo valid terlebih dahulu
            if diskon_code:
                query_str = f"""
                    SELECT * FROM promo
                    JOIN diskon ON kode_diskon = kode_promo
                    WHERE kode_promo = '{diskon_code}' AND tglakhirberlaku >= current_date
                """
                promo_data = query(query_str)

                if promo_data:
                    promo = promo_data[0]
                    min_transaksi = float(promo['mintrpemesanan'])
                    potongan = float(promo['potongan'])
                    berhasil_diskon = True

                    if float(price) < min_transaksi:
                        # Promo tidak valid (harga kurang dari min_transaksi)
                        return JsonResponse({'success': False, 'message': 'Harga tidak memenuhi syarat minimum transaksi.'})
                    else:
                        harga_akhir -= potongan

                else:
                    # Jika promo tidak ditemukan, cek apakah kode diskon valid
                    query_diskon = f"""
                    SELECT * FROM tr_pembelian_voucher
                    JOIN diskon ON kode_diskon = idvoucher
                    JOIN voucher ON kode_voucher = idvoucher
                    WHERE idpelanggan = '{penggunalogin['id_user']}' AND idvoucher = '{diskon_code}' AND tglakhir >= current_date AND tglawal <= current_date AND telahdigunakan < kuotapenggunaan
                    ORDER BY tglawal ASC, tglakhir ASC
                    """
                    diskon_data = query(query_diskon)

                    if diskon_data:
                        diskon = diskon_data[0]  # Ambil data diskon pertama (jika ada)
                        min_transaksi = float(diskon['mintrpemesanan'])
                        potongan = float(diskon['potongan'])
                        berhasil_diskon = True

                        if float(price) < min_transaksi:
                            # Diskon tidak valid (harga kurang dari min_transaksi)
                            return JsonResponse({'success': False, 'message': 'Harga tidak memenuhi syarat minimum transaksi.'})
                        else:
                            harga_akhir -= potongan  # Kurangi harga dengan potongan
                            query_str = f"""
                            UPDATE tr_pembelian_voucher 
                            SET telahdigunakan = telahdigunakan + 1
                            WHERE id_tr_pembelian_voucher = '{diskon['id_tr_pembelian_voucher']}'
                            """
                            query(query_str)
                    else:
                        # Jika kode diskon juga tidak valid
                        return JsonResponse({'success': False, 'message': 'Kode diskon/promo tidak valid.'})

            id_pemesanan = uuid.uuid4()
            # Simpan pemesanan ke database
            if(berhasil_diskon):
                query_str = f"""
                INSERT INTO tr_pemesanan_jasa 
                (idkategorijasa, idpelanggan, id_tr_pemesanan_jasa, totalbiaya, tglpemesanan, idmetodebayar, sesi, iddiskon) 
                VALUES 
                ('{subcategory_id}', '{penggunalogin['id_user']}', '{id_pemesanan}', '{harga_akhir}', current_date, '{metode_bayar}', '{session}', '{diskon_code}')
                """
            else:
                query_str = f"""
                INSERT INTO tr_pemesanan_jasa 
                (idkategorijasa, idpelanggan, id_tr_pemesanan_jasa, totalbiaya, tglpemesanan, idmetodebayar, sesi, iddiskon) 
                VALUES 
                ('{subcategory_id}', '{penggunalogin['id_user']}', '{id_pemesanan}', '{harga_akhir}', current_date, '{metode_bayar}', '{session}', null)
                """
            
            query(query_str)

            if metode_bayar == 'ab9aab5e-5706-4c35-8099-765b7f41a925':
                query_str = f"""
                    insert into tr_pemesanan_status values('{id_pemesanan}', '40bd17f1-779d-42e7-bcd3-26390d5b251c', current_date)
                    """

hijau/templates/create_pesanan.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'navbar_pengguna.html' %}
{% endblock navbar %}

{% block content %}
<div class="container mx-auto p-6 bg-white rounded-lg shadow-lg mt-8 max-w-xl">
    <h2 class="text-3xl font-semibold text-gray-800 mb-6 text-center">Formulir Pemesanan Jasa</h2>
    <form id="pemesananForm" method="post">
        {% csrf_token %}

        <!-- Tanggal Pemesanan -->
        <div class="mb-6">
            <label class="text-lg font-medium block mb-2">Tanggal Pemesanan</label>
            <div class="relative bg-gray-100 border border-gray-300 rounded-lg p-3 text-gray-800">
                {{ tanggal_pemesanan|date:"d/m/Y" }}
            </div>
        </div>

        <!-- Kode Diskon -->
        <div class="mb-6">
            <label for="id_diskon" class="text-lg font-medium block mb-2">Kode Promo</label>
            <div class="relative">
                {{ form.diskon }}
            </div>
        </div>

        <!-- Total Pembayaran -->
        <div class="mb-6">
            <label class="text-lg font-medium block mb-2">Total Pembayaran</label>
            <div class="relative bg-yellow-100 border border-yellow-300 rounded-lg p-3 text-gray-800 font-semibold">
                Rp {{ harga }}
            </div>
        </div>

        <!-- Metode Pembayaran -->
        <div class="mb-6">
            <label for="id_metode_bayar" class="text-lg font-medium block mb-2">Metode Pembayaran</label>
            <div class="relative">
                {{ form.metode_bayar }}
            </div>
        </div>

        <!-- Div untuk Pesan Error -->
        <div id="errorMessage" class="hidden bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
            <span id="errorText"></span>
        </div>

        <!-- Submit Button -->
        <div class="mt-8 text-center">
            <button type="submit" class="w-full sm:w-auto px-6 py-3 bg-[#2C5F59] text-white font-semibold rounded-lg hover:text-[#2C5F59] transition duration-200">
                Submit
            </button>
        </div>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#pemesananForm').on('submit', function (e) {
            e.preventDefault(); // Cegah form agar tidak refresh halaman

            $.ajax({
                type: 'POST',
                url: '', // Form dikirim ke URL yang sama
                data: $(this).serialize(), // Serialisasi data form
                dataType: 'json',
                success: function (response) {
                    if (response.success) {
                        // Jika sukses, redirect atau tampilkan pesan sukses
                        window.location.href = '/hijau/view-pemesanan'; // Ganti dengan URL tujuan
                    } else {
                        // Tampilkan pesan error
                        $('#errorMessage').removeClass('hidden'); // Tampilkan div pesan error
                        $('#errorText').text(response.message); // Masukkan pesan error
                    }
                },
                error: function () {
                    // Tampilkan pesan error jika AJAX gagal
                    $('#errorMessage').removeClass('hidden');
                    $('#errorText').text('Terjadi kesalahan saat memproses data.');
                }
            });
        });
    });
</script>
{% endblock %}

hijau/templates/homepage.html
{% extends 'base.html' %}

{% block navbar %}
    {% if penggunalogin.role == 'pekerja' %}
        {% include 'navbar_pekerja.html' %}
    {% else %}
        {% include 'navbar_pengguna.html' %}
    {% endif %}
{% endblock navbar %}

{% block content %}
<div class="bg-gray-100 min-h-screen py-8">
    <div class="container mx-auto p-6 bg-white rounded-lg shadow-lg max-w-xl">
        <h1 class="text-3xl font-bold text-center mb-6">Daftar Kategori Jasa</h1>

        <!-- Filter Dropdown Kategori -->
        <div class="mb-6">
            <label for="category-dropdown" class="text-lg font-medium block mb-2">Pilih Kategori:</label>
            <select id="category-dropdown" class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#2C5F59]">
                <option value="">Pilih Kategori</option>
                {% for category in categories %}
                    <option value="{{ category.id_kategori_jasa }}">{{ category.namakategori }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Search Bar for Subcategories -->
        <div class="mb-6">
            <label for="subcategory-search" class="text-lg font-medium block mb-2">Cari Subkategori:</label>
            <input type="text" id="subcategory-search" class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#2C5F59]" placeholder="Cari subkategori...">
        </div>

        <!-- Search Button -->
        <div class="mb-6 text-center">
            <button id="search-button" class="w-full sm:w-auto px-6 py-3 bg-[#2C5F59] hover:text-[#2C5F59] text-white font-semibold rounded-lg transition duration-200">Cari</button>
        </div>

        <!-- Daftar Subkategori per Kategori -->
        <div id="subcategory-list">
            {% for category in categories %}
                <div id="category-{{ category.id_kategori_jasa }}" class="subcategory-category mb-6">
                    <h2 class="text-2xl font-semibold text-gray-800 mb-4">{{ category.namakategori }}</h2>
                    <ul>
                        {% for subcategory in subcategories %}
                            {% if subcategory.kategorijasaid == category.id_kategori_jasa %}
                                <li class="subcategory-item mb-4">
                                    <div class="flex justify-between items-center">
                                        <!-- Tampilkan tautan sesuai peran pengguna -->
                                        {% if penggunalogin.role == 'pekerja' %}
                                            <a href="{% url 'hijau:subcategory_detail_user' category.id_kategori_jasa subcategory.nama %}" class="text-#2F4F4F hover:text-green-800 font-medium">
                                                {{ subcategory.nama }} - {{ subcategory.deskripsi }}
                                            </a>
                                        {% else %}
                                            <a href="{% url 'hijau:subcategory_detail_user' category.id_kategori_jasa subcategory.nama %}" class="text-#2F4F4F hover:text-green-800 font-medium">
                                                {{ subcategory.nama }} - {{ subcategory.deskripsi }}
                                            </a>
                                        {% endif %}
                                    </div>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<script>
    // Menangani filter kategori
    document.getElementById('category-dropdown').addEventListener('change', function() {
        var selectedCategory = this.value;
        var subcategoryList = document.getElementById('subcategory-list');
        
        // Menyembunyikan semua subkategori terlebih dahulu
        var subcategorySections = subcategoryList.querySelectorAll('.subcategory-category');
        subcategorySections.forEach(function(section) {
            section.style.display = 'none';
        });
        
        // Menampilkan subkategori sesuai kategori yang dipilih
        if (selectedCategory) {
            var selectedCategoryElement = document.getElementById('category-' + selectedCategory);
            selectedCategoryElement.style.display = 'block';
        } else {
            // Tampilkan semua subkategori jika tidak ada kategori yang dipilih
            subcategorySections.forEach(function(section) {
                section.style.display = 'block';
            });
        }
    });

    // Menangani pencarian subkategori berdasarkan tombol klik
    document.getElementById('search-button').addEventListener('click', function() {
        var searchTerm = document.getElementById('subcategory-search').value.toLowerCase();
        var subcategorySections = document.querySelectorAll('.subcategory-category');
        
        subcategorySections.forEach(function(section) {
            var subcategoryItems = section.querySelectorAll('.subcategory-item');
            var categoryHasVisibleSubcategory = false;

            subcategoryItems.forEach(function(item) {
                var subcategorynama = item.querySelector('a').textContent.toLowerCase();
                if (subcategorynama.includes(searchTerm)) {
                    item.style.display = 'block';
                    categoryHasVisibleSubcategory = true;
                } else {
                    item.style.display = 'none';
                }
            });

            // Tampilkan atau sembunyikan kategori berdasarkan apakah ada subkategori yang cocok
            if (categoryHasVisibleSubcategory) {
                section.style.display = 'block';
            } else {
                section.style.display = 'none';
            }
        });
    });
</script>
{% endblock %}

hijau/templates/subcategory_user.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'navbar_pengguna.html' %}
{% endblock navbar %}

{% block content %}
<div class="container mx-auto p-6 bg-white rounded-lg shadow-lg mt-8 max-w-xl">
    <h1 class="text-3xl font-bold text-center text-gray-800 mb-6">{{ subcategory.nama }}</h1>
    <p class="text-lg text-gray-600 mb-6"><strong>Kategori:</strong> {{ category_name }}</p>
    <p class="text-md text-gray-700 mb-6">{{ subcategory.deskripsi }}</p>

    <h2 class="text-2xl font-semibold text-gray-800 mb-4">Pilihan Sesi Layanan</h2>
    <ul class="list-disc space-y-4 text-gray-700">
        {% for session in sessions %}
            <li class="flex justify-between items-center">
                <span>{{ session.sesi }}. Rp {{ session.harga }}</span>
                <a href="{% url 'hijau:create_pemesanan' session.id_subkategori session.sesi session.harga %}" 
                   class="bg-[#2F4F4F] text-white px-4 py-2 rounded transition duration-200">
                    Pesan
                </a>
            </li>
        {% endfor %}
    </ul>

    <h2 class="text-2xl font-semibold text-gray-800 mb-6 mt-8">Daftar Pekerja</h2>
    <ul class="space-y-4 text-gray-700">
        {% for worker in workers %}
            <li>
                <a href="{% url 'hijau:worker_detail' worker.nama %}" class="text-[#2F4F4F] hover:text-green-800 font-medium">
                    {{ worker.nama }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <h2 class="text-2xl font-semibold text-[#283D3B] mb-6 mt-8">Testimoni</h2>
    <ul class="space-y-4">
        {% if testimonials %}
            {% for testimonial in testimonials %}
                <li class="bg-[#F3EBE0] bg-opacity-50 rounded-lg p-4 border border-[#2C5F59] shadow-sm">
                    <div class="flex justify-between items-start mb-2">
                        <div>
                            <strong class="font-semibold text-[#283D3B]">{{ testimonial.namapengguna }}</strong>
                            <span class="text-[#2C5F59] text-sm">({{ testimonial.tanggal }})</span>
                        </div>
                        <div class="text-[#00DFC9]">
                            {{ testimonial.rating }} ★
                        </div>
                    </div>
                    <p class="italic text-[#283D3B] mb-2">"{{ testimonial.teks }}"</p>
                    <span class="text-[#2C5F59] text-sm">Pekerja: {{ testimonial.namapekerja }}</span>
                </li>
            {% endfor %}
        {% else %}
            <p>Belum ada testimoni</p>
        {% endif %}
    </ul>
</div>
{% endblock %}

hijau/templates/view_pemesanan.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'navbar_pengguna.html' %}
{% endblock navbar %}

{% block content %}
<div class="container mx-auto p-6 bg-white rounded-lg shadow-lg mt-8 max-w-xl">
    <h2 class="text-3xl font-bold text-gray-800 mb-6 text-center">Daftar Pesanan Jasa</h2>
    
    {% if pesanan %}
        <ul class="space-y-6">
            {% for pesanan in pesanan %}
                <li class="bg-white p-6 rounded-lg shadow-md border border-gray-200">
                    <h3 class="text-2xl font-bold text-gray-800 mb-2">{{ pesanan.session_name }}</h3>
                    <h3 class="text-xl font-semibold text-green-500 mb-2">Rp {{ pesanan.session_price }}</h3>
                    {% if pesanan.status != 'Mencari Pekerja Terdekat' and pesanan.status != 'Menunggu Pembayaran' and pesanan.status != 'Pesanan dibatalkan'%}
                        <p class="text-gray-700 flex items-center">    
                            <svg class="w-5 h-5 mr-2 text-blue-500" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>
                            Nama Pekerja: <span class="ml-1 font-medium">{{ pesanan.worker_name }}</span>
                        </p>
                    {% endif %}
                    <p class="text-gray-700 flex items-center">
                        <svg class="w-5 h-5 mr-2 text-yellow-500" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20 6h-2.586l-.707-.707c-.63-.63-1.707-.184-1.707.707v3h-5v-3c0-.891-1.077-1.338-1.707-.707l-.707.707h-2.586c-1.104 0-2 .896-2 2v10c0 1.104.896 2 2 2h16c1.104 0 2-.896 2-2v-10c0-1.104-.896-2-2-2zm-10 8h-2v-2h2v2zm8 0h-6v-2h6v2z"/></svg>
                        Status: <span class="ml-1 font-semibold">{{ pesanan.status|capfirst }}</span>
                    </p>

                    <!-- Tombol diatur dengan Flexbox -->
                    <div class="flex flex-col gap-4 mt-4">
                        {% if pesanan.status == 'Mencari Pekerja Terdekat' or pesanan.status == 'Menunggu Pembayaran' %}
                            <a href="{% url 'hijau:batal_pemesanan' pesanan.id_pemesanan %}" 
                               class="bg-red-500 text-white px-6 py-3 rounded-lg hover:bg-red-600 transition duration-200 text-center">
                                Batalkan Pesanan
                            </a>
                        {% endif %}
                        {% if pesanan.status == 'Pesanan selesai' and pesanan.testimoni == '' %}
                            <a href="{% url 'biru:testimoni_form' pesanan.id_pemesanan %}"
                            class="bg-green-500 text-white px-6 py-3 rounded-lg hover:bg-green-600 transition duration-200 text-center">
                                Buat Testimoni
                            </a>
                        {% endif %}
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="text-center mt-12">
            <p class="text-lg text-gray-600">Anda belum memesan jasa.</p>
            <div class="mt-6">
                <button 
                    onclick="window.location.href='{% url 'hijau:homepage' %}'" 
                    class="w-full bg-[#2F4F4F] text-white py-3 rounded-lg hover:bg-[#1E3D3D] transition duration-200">
                    Pesan Jasa
                </button>
            </div>
        </div>        
    {% endif %}
</div>
{% endblock %}